import { Injectable } from '@angular/core';
import { Difficulty, TriviaCategory, TriviaQuestion } from '../models';

const QUESTIONS: TriviaQuestion[] = [
  // ===== גן =====
  { id:  1, difficulty: 'gan', category: 'math',    points: 1,  question: 'כמה זה 1 + 1?',                   answers: ['1', '2', '3', '4'],                        correctIndex: 1 },
  { id:  2, difficulty: 'gan', category: 'math',    points: 1,  question: 'כמה זה 2 + 2?',                   answers: ['3', '4', '5', '6'],                        correctIndex: 1 },
  { id:  3, difficulty: 'gan', category: 'science', points: 1,  question: 'כמה רגליים יש לכלב?',             answers: ['2', '4', '6', '8'],                        correctIndex: 1 },
  { id:  4, difficulty: 'gan', category: 'science', points: 1,  question: 'איזה צבע הוא השמש?',              answers: ['כחול', 'ירוק', 'צהוב', 'אדום'],            correctIndex: 2 },
  { id:  5, difficulty: 'gan', category: 'science', points: 1,  question: 'מה עושים דגים במים?',             answers: ['הולכים', 'שוחים', 'עפים', 'ישנים'],        correctIndex: 1 },
  { id:  6, difficulty: 'gan', category: 'math',    points: 1,  question: 'כמה זה 3 + 1?',                   answers: ['2', '3', '4', '5'],                        correctIndex: 2 },
  { id:  7, difficulty: 'gan', category: 'science', points: 1,  question: 'כמה רגליים לציפור?',              answers: ['2', '4', '6', '0'],                        correctIndex: 0 },
  { id:  8, difficulty: 'gan', category: 'math',    points: 1,  question: 'כמה זה 5 - 2?',                   answers: ['1', '2', '3', '4'],                        correctIndex: 2 },
  { id:  9, difficulty: 'gan', category: 'science', points: 1,  question: 'מה צבע הדשא?',                    answers: ['אדום', 'כחול', 'ירוק', 'צהוב'],            correctIndex: 2 },
  { id: 10, difficulty: 'gan', category: 'math',    points: 1,  question: 'כמה זה 4 + 3?',                   answers: ['5', '6', '7', '8'],                        correctIndex: 2 },
  { id: 11, difficulty: 'gan', category: 'science', points: 1,  question: 'כמה אוזניים יש לארנבת?',          answers: ['1', '2', '3', '4'],                        correctIndex: 1 },
  { id: 12, difficulty: 'gan', category: 'math',    points: 1,  question: 'כמה זה 10 - 3?',                  answers: ['5', '6', '7', '8'],                        correctIndex: 2 },
  { id: 13, difficulty: 'gan', category: 'science', points: 1,  question: 'מה בעל החיים הכי גדול?',          answers: ['פיל', 'לווייתן', 'ג׳ירפה', 'קרינוקרוס'],  correctIndex: 1 },
  { id: 14, difficulty: 'gan', category: 'math',    points: 1,  question: 'כמה זה 2 + 5?',                   answers: ['6', '7', '8', '9'],                        correctIndex: 1 },
  { id: 15, difficulty: 'gan', category: 'science', points: 1,  question: 'איזה עונה קרה?',                  answers: ['קיץ', 'אביב', 'חורף', 'סתיו'],            correctIndex: 2 },
  { id: 16, difficulty: 'gan', category: 'math',    points: 1,  question: 'כמה זה 6 + 2?',                   answers: ['7', '8', '9', '10'],                       correctIndex: 1 },
  { id: 17, difficulty: 'gan', category: 'science', points: 1,  question: 'מה עצים נותנים לנו לנשום?',       answers: ['מים', 'אבק', 'חמצן', 'חנקן'],              correctIndex: 2 },
  { id: 18, difficulty: 'gan', category: 'math',    points: 1,  question: 'כמה זה 9 - 4?',                   answers: ['3', '4', '5', '6'],                        correctIndex: 2 },
  { id: 19, difficulty: 'gan', category: 'science', points: 1,  question: 'מה עושה פרפר?',                   answers: ['שוחה', 'עף', 'קופץ', 'חופר'],              correctIndex: 1 },
  { id: 20, difficulty: 'gan', category: 'math',    points: 1,  question: 'כמה זה 1 + 4?',                   answers: ['3', '4', '5', '6'],                        correctIndex: 2 },

  // ===== א-ב =====
  { id: 21, difficulty: '1-2', category: 'math',    points: 1, question: 'כמה זה 5 + 7?',                   answers: ['10', '11', '12', '13'],                    correctIndex: 2 },
  { id: 22, difficulty: '1-2', category: 'math',    points: 1, question: 'כמה זה 8 × 2?',                   answers: ['14', '16', '18', '20'],                    correctIndex: 1 },
  { id: 23, difficulty: '1-2', category: 'science', points: 1, question: 'מה קורה לקרח כשחם?',              answers: ['מתקשה', 'נמס', 'נעלם', 'צובע'],            correctIndex: 1 },
  { id: 24, difficulty: '1-2', category: 'science', points: 1, question: 'כמה שניות יש בדקה?',              answers: ['30', '45', '60', '100'],                   correctIndex: 2 },
  { id: 25, difficulty: '1-2', category: 'math',    points: 1, question: 'כמה זה 14 - 6?',                  answers: ['6', '7', '8', '9'],                        correctIndex: 2 },
  { id: 26, difficulty: '1-2', category: 'science', points: 1, question: 'איזה פרי צהוב וחמוץ?',            answers: ['תפוח', 'לימון', 'ענב', 'אבטיח'],           correctIndex: 1 },
  { id: 27, difficulty: '1-2', category: 'math',    points: 1, question: 'כמה זה 3 × 4?',                   answers: ['10', '11', '12', '13'],                    correctIndex: 2 },
  { id: 28, difficulty: '1-2', category: 'science', points: 1, question: 'כמה דקות יש בשעה?',               answers: ['30', '60', '90', '100'],                   correctIndex: 1 },
  { id: 29, difficulty: '1-2', category: 'math',    points: 1, question: 'כמה זה 20 + 15?',                 answers: ['30', '35', '40', '45'],                    correctIndex: 1 },
  { id: 30, difficulty: '1-2', category: 'science', points: 1, question: 'כמה ימים בשבוע?',                 answers: ['5', '6', '7', '8'],                        correctIndex: 2 },
  { id: 31, difficulty: '1-2', category: 'math',    points: 1, question: 'כמה זה 9 × 3?',                   answers: ['18', '21', '27', '30'],                    correctIndex: 2 },
  { id: 32, difficulty: '1-2', category: 'science', points: 1, question: 'מה הצמח צריך כדי לגדול?',         answers: ['מלח', 'שמן', 'אור ומים', 'חלב'],           correctIndex: 2 },
  { id: 33, difficulty: '1-2', category: 'math',    points: 1, question: 'כמה זה 50 - 18?',                 answers: ['28', '30', '32', '34'],                    correctIndex: 2 },
  { id: 34, difficulty: '1-2', category: 'science', points: 1, question: 'כמה חודשים בשנה?',                answers: ['10', '11', '12', '13'],                    correctIndex: 2 },
  { id: 35, difficulty: '1-2', category: 'math',    points: 1, question: 'כמה זה 6 × 5?',                   answers: ['25', '28', '30', '35'],                    correctIndex: 2 },
  { id: 36, difficulty: '1-2', category: 'science', points: 1, question: 'מה גדול יותר: ק"ג או גרם?',       answers: ['גרם', 'שווה', 'ק"ג', 'תלוי'],              correctIndex: 2 },
  { id: 37, difficulty: '1-2', category: 'math',    points: 1, question: 'כמה זה 100 - 37?',                answers: ['57', '61', '63', '73'],                    correctIndex: 2 },
  { id: 38, difficulty: '1-2', category: 'science', points: 1, question: 'באיזה עונה פורחים פרחים?',        answers: ['חורף', 'קיץ', 'אביב', 'סתיו'],            correctIndex: 2 },
  { id: 39, difficulty: '1-2', category: 'math',    points: 1, question: 'כמה זה 7 × 7?',                   answers: ['42', '45', '49', '56'],                    correctIndex: 2 },
  { id: 40, difficulty: '1-2', category: 'science', points: 1, question: 'מה גורם לקשת בענן?',              answers: ['רוח', 'אור שמש + גשם', 'ברק', 'שלג'],     correctIndex: 1 },

  // ===== ג-ד =====
  { id: 41, difficulty: '3-4', category: 'math',    points: 1, question: 'כמה זה 7 × 8?',                   answers: ['48', '54', '56', '63'],                    correctIndex: 2 },
  { id: 42, difficulty: '3-4', category: 'math',    points: 1, question: 'כמה זה 144 ÷ 12?',                answers: ['10', '11', '12', '13'],                    correctIndex: 2 },
  { id: 43, difficulty: '3-4', category: 'science', points: 1, question: 'באיזו טמפרטורה מים רותחים?',      answers: ['50°C', '75°C', '100°C', '120°C'],          correctIndex: 2 },
  { id: 44, difficulty: '3-4', category: 'science', points: 1, question: 'מה הפלנטה הקרובה ביותר לשמש?',   answers: ['כדור הארץ', 'ונוס', 'מאדים', 'מרקורי'],   correctIndex: 3 },
  { id: 45, difficulty: '3-4', category: 'math',    points: 1, question: 'כמה זה 25% מ-200?',               answers: ['25', '40', '50', '75'],                    correctIndex: 2 },
  { id: 46, difficulty: '3-4', category: 'science', points: 1, question: 'מה נוסחת המים?',                  answers: ['CO₂', 'H₂O', 'O₂', 'NaCl'],               correctIndex: 1 },
  { id: 47, difficulty: '3-4', category: 'math',    points: 1, question: 'מה שורש ריבועי של 81?',           answers: ['7', '8', '9', '10'],                       correctIndex: 2 },
  { id: 48, difficulty: '3-4', category: 'science', points: 1, question: 'כמה שעות ביממה?',                 answers: ['12', '24', '36', '48'],                    correctIndex: 1 },
  { id: 49, difficulty: '3-4', category: 'math',    points: 1, question: 'כמה זה 13 × 13?',                 answers: ['156', '169', '172', '180'],                correctIndex: 1 },
  { id: 50, difficulty: '3-4', category: 'science', points: 1, question: 'כמה כוכבי לכת במערכת השמש?',      answers: ['7', '8', '9', '10'],                       correctIndex: 1 },
  { id: 51, difficulty: '3-4', category: 'math',    points: 1, question: 'כמה זה 360 ÷ 4?',                 answers: ['80', '90', '100', '120'],                  correctIndex: 1 },
  { id: 52, difficulty: '3-4', category: 'science', points: 1, question: 'מה עושה הכלורופיל בצמח?',         answers: ['שואב מים', 'מייצר אנרגיה מאור', 'מושך חרקים', 'מגן מקור'],  correctIndex: 1 },
  { id: 53, difficulty: '3-4', category: 'math',    points: 1, question: 'מה היקף ריבוע עם צלע 7?',         answers: ['21', '28', '35', '49'],                    correctIndex: 1 },
  { id: 54, difficulty: '3-4', category: 'science', points: 1, question: 'מה כוח המשיכה על כדור הארץ?',     answers: ['5 מ/ש²', '9.8 מ/ש²', '15 מ/ש²', '20 מ/ש²'], correctIndex: 1 },
  { id: 55, difficulty: '3-4', category: 'math',    points: 1, question: 'כמה זה 1000 - 375?',              answers: ['515', '625', '635', '725'],                correctIndex: 1 },
  { id: 56, difficulty: '3-4', category: 'science', points: 1, question: 'מאיזה חומר עשוי עצם?',            answers: ['ברזל', 'סידן', 'פחמן', 'אשלגן'],           correctIndex: 1 },
  { id: 57, difficulty: '3-4', category: 'math',    points: 1, question: 'כמה אלכסונים למלבן?',             answers: ['1', '2', '3', '4'],                        correctIndex: 1 },
  { id: 58, difficulty: '3-4', category: 'science', points: 1, question: 'מה הגז הנפוץ ביותר באוויר?',      answers: ['חמצן', 'פחמן דו-חמצני', 'חנקן', 'מימן'],  correctIndex: 2 },
  { id: 59, difficulty: '3-4', category: 'math',    points: 1, question: 'כמה זה 4³ (4 בחזקת 3)?',          answers: ['12', '32', '64', '128'],                   correctIndex: 2 },
  { id: 60, difficulty: '3-4', category: 'science', points: 1, question: 'כמה ריאות יש לאדם?',              answers: ['1', '2', '3', '4'],                        correctIndex: 1 },

  // ===== ה-ו =====
  { id: 61, difficulty: '5-6', category: 'math',    points: 1, question: 'כמה זה 15% מ-340?',               answers: ['34', '51', '68', '85'],                    correctIndex: 1 },
  { id: 62, difficulty: '5-6', category: 'math',    points: 1, question: 'מה נוסחת שטח המעגל?',             answers: ['2πr', 'πr²', 'πd', '4πr²'],               correctIndex: 1 },
  { id: 63, difficulty: '5-6', category: 'science', points: 1, question: 'כמה פרוטונים יש בפחמן (C)?',      answers: ['4', '6', '8', '12'],                       correctIndex: 1 },
  { id: 64, difficulty: '5-6', category: 'science', points: 1, question: 'מה מהירות האור?',                 answers: ['300,000 קמ/ש', '150,000 קמ/ש', '600,000 קמ/ש', '30,000 קמ/ש'], correctIndex: 0 },
  { id: 65, difficulty: '5-6', category: 'math',    points: 1, question: 'כמה זה 2⁸?',                      answers: ['128', '256', '512', '64'],                 correctIndex: 1 },
  { id: 66, difficulty: '5-6', category: 'science', points: 1, question: 'מה חוק ניוטון הראשון?',           answers: ['F=ma', 'גוף במנוחה נשאר במנוחה', 'לכל פעולה יש תגובה', 'כוח משיכה'], correctIndex: 1 },
  { id: 67, difficulty: '5-6', category: 'math',    points: 1, question: 'כמה זה √169?',                    answers: ['11', '12', '13', '14'],                    correctIndex: 2 },
  { id: 68, difficulty: '5-6', category: 'science', points: 1, question: 'כמה יסודות בטבלה המחזורית?',      answers: ['108', '112', '118', '126'],                correctIndex: 2 },
  { id: 69, difficulty: '5-6', category: 'math',    points: 1, question: 'כמה זה 7! (7 עצרת)?',             answers: ['720', '2520', '5040', '40320'],             correctIndex: 2 },
  { id: 70, difficulty: '5-6', category: 'science', points: 1, question: 'מה המשוואה E=mc² מייצגת?',        answers: ['אנרגיה קינטית', 'המרת מסה לאנרגיה', 'כוח גרביטציה', 'לחץ גז'], correctIndex: 1 },
  { id: 71, difficulty: '5-6', category: 'math',    points: 1, question: 'כמה זה 30% מ-450?',               answers: ['90', '115', '135', '145'],                 correctIndex: 2 },
  { id: 72, difficulty: '5-6', category: 'science', points: 1, question: 'מה מספר האטומי של זהב (Au)?',     answers: ['47', '74', '79', '82'],                    correctIndex: 2 },
  { id: 73, difficulty: '5-6', category: 'math',    points: 1, question: 'מה שיפוע הישר y = 3x - 5?',       answers: ['-5', '3', '-3', '5'],                      correctIndex: 1 },
  { id: 74, difficulty: '5-6', category: 'science', points: 1, question: 'כמה כרומוזומים בתא אנושי?',       answers: ['23', '46', '48', '92'],                    correctIndex: 1 },
  { id: 75, difficulty: '5-6', category: 'math',    points: 1, question: 'כמה זה log₁₀(1000)?',             answers: ['2', '3', '4', '10'],                       correctIndex: 1 },
  { id: 76, difficulty: '5-6', category: 'science', points: 1, question: 'מה pH של מים טהורים?',            answers: ['5', '6', '7', '8'],                        correctIndex: 2 },
  { id: 77, difficulty: '5-6', category: 'math',    points: 1, question: 'כמה צלעות לאוקטגון?',             answers: ['6', '7', '8', '9'],                        correctIndex: 2 },
  { id: 78, difficulty: '5-6', category: 'science', points: 1, question: 'מה תהליך הפוטוסינתזה מייצר?',     answers: ['CO₂ + מים', 'גלוקוז + חמצן', 'חנקן + מים', 'אלכוהול'], correctIndex: 1 },
  { id: 79, difficulty: '5-6', category: 'math',    points: 1, question: 'כמה זה sin(90°)?',                answers: ['0', '0.5', '1', '√2/2'],                   correctIndex: 2 },
  { id: 80, difficulty: '5-6', category: 'science', points: 1, question: 'מה חוק אוהם?',                    answers: ['V=IR', 'P=mv', 'F=ma', 'E=mc²'],           correctIndex: 0 },

  // ===== ז-ח =====
  { id:  81, difficulty: '7-8', category: 'math',    points: 1, question: 'פתור: 2x + 6 = 14',                              answers: ['2', '3', '4', '5'],                                     correctIndex: 2 },
  { id:  82, difficulty: '7-8', category: 'math',    points: 1, question: 'מה שיפוע הישר y = -3x + 2?',                     answers: ['-3', '2', '3', '-2'],                                   correctIndex: 0 },
  { id:  83, difficulty: '7-8', category: 'math',    points: 1, question: 'כמה זה (-4)²?',                                  answers: ['-16', '-8', '8', '16'],                                 correctIndex: 3 },
  { id:  84, difficulty: '7-8', category: 'math',    points: 1, question: 'מה שטח משולש עם בסיס 8 וגובה 5?',               answers: ['13', '20', '40', '80'],                                 correctIndex: 1 },
  { id:  85, difficulty: '7-8', category: 'math',    points: 1, question: 'כמה זה 3² + 4²?',                                answers: ['14', '25', '49', '7'],                                  correctIndex: 1 },
  { id:  86, difficulty: '7-8', category: 'math',    points: 1, question: 'מה ה-LCM של 6 ו-9?',                             answers: ['3', '18', '27', '54'],                                  correctIndex: 1 },
  { id:  87, difficulty: '7-8', category: 'math',    points: 1, question: 'פשט: (x²·x³)',                                   answers: ['x⁵', 'x⁶', '2x⁵', 'x'],                               correctIndex: 0 },
  { id:  88, difficulty: '7-8', category: 'math',    points: 1, question: 'כמה אלכסונים למצולע עם 6 קודקודים?',            answers: ['6', '9', '12', '15'],                                   correctIndex: 1 },
  { id:  89, difficulty: '7-8', category: 'math',    points: 1, question: 'מה היחס בין היקף לקוטר?',                       answers: ['e', 'π', '√2', '2'],                                    correctIndex: 1 },
  { id:  90, difficulty: '7-8', category: 'math',    points: 1, question: 'כמה זה 0.25 × 0.4?',                             answers: ['0.01', '0.1', '0.6', '1'],                              correctIndex: 1 },
  { id:  91, difficulty: '7-8', category: 'science', points: 1, question: 'מה הסמל הכימי של ברזל?',                        answers: ['Br', 'Fe', 'Fr', 'Ir'],                                 correctIndex: 1 },
  { id:  92, difficulty: '7-8', category: 'science', points: 1, question: 'כמה אלקטרונים בשכבה הראשונה של אטום?',          answers: ['2', '4', '8', '18'],                                    correctIndex: 0 },
  { id:  93, difficulty: '7-8', category: 'science', points: 1, question: 'מה ה-DNA עשוי ממנו?',                            answers: ['חומצות אמינו', 'נוקלאוטידים', 'שומנים', 'פחמימות'],    correctIndex: 1 },
  { id:  94, difficulty: '7-8', category: 'science', points: 1, question: 'מה חוק שימור האנרגיה?',                         answers: ['אנרגיה נוצרת מחום', 'אנרגיה לא נברא ולא נאבד', 'אנרגיה = מסה', 'אנרגיה = כוח × זמן'], correctIndex: 1 },
  { id:  95, difficulty: '7-8', category: 'science', points: 1, question: 'מה האיבר שמייצר אינסולין?',                    answers: ['כבד', 'כליה', 'לבלב', 'ריאה'],                          correctIndex: 2 },
  { id:  96, difficulty: '7-8', category: 'science', points: 1, question: 'מה ההבדל בין תא חיידקי לתא יוקריוטי?',         answers: ['גודל', 'יש/אין גרעין', 'צבע', 'מספר כרומוזומים'],       correctIndex: 1 },
  { id:  97, difficulty: '7-8', category: 'science', points: 1, question: 'כמה ניוטון שווה 1 קילוגרם-כוח בקירוב?',        answers: ['1', '9.8', '100', '980'],                               correctIndex: 1 },
  { id:  98, difficulty: '7-8', category: 'science', points: 1, question: 'מה הסמל הכימי של נתרן?',                       answers: ['N', 'Na', 'Ne', 'Nt'],                                  correctIndex: 1 },
  { id:  99, difficulty: '7-8', category: 'science', points: 1, question: 'מה תפקיד כדוריות הדם הלבנות?',                 answers: ['נשיאת חמצן', 'הגנה מפני מחלות', 'קרישת דם', 'עיכול'], correctIndex: 1 },
  { id: 100, difficulty: '7-8', category: 'science', points: 1, question: 'מה סוג הגל של אור?',                            answers: ['גל מכני', 'גל אורך', 'גל אלקטרומגנטי', 'גל קול'],       correctIndex: 2 },

  // ===== ט-י =====
  { id: 101, difficulty: '9-10', category: 'math',    points: 1, question: 'פתור: x² - 5x + 6 = 0',                        answers: ['x=1,6', 'x=2,3', 'x=-2,-3', 'x=3,4'],                  correctIndex: 1 },
  { id: 102, difficulty: '9-10', category: 'math',    points: 1, question: 'מה הנגזרת של x³?',                             answers: ['x²', '3x', '3x²', 'x⁴/4'],                             correctIndex: 2 },
  { id: 103, difficulty: '9-10', category: 'math',    points: 1, question: 'מה cos(0°)?',                                  answers: ['0', '0.5', '1', '√2/2'],                                correctIndex: 2 },
  { id: 104, difficulty: '9-10', category: 'math',    points: 1, question: 'כמה זה log₂(64)?',                             answers: ['4', '5', '6', '8'],                                     correctIndex: 2 },
  { id: 105, difficulty: '9-10', category: 'math',    points: 1, question: 'מה שטח המעגל כאשר r=5?',                      answers: ['10π', '20π', '25π', '50π'],                             correctIndex: 2 },
  { id: 106, difficulty: '9-10', category: 'math',    points: 1, question: 'מה ערך sin(30°)?',                             answers: ['0', '√3/2', '1/2', '1'],                                correctIndex: 2 },
  { id: 107, difficulty: '9-10', category: 'math',    points: 1, question: 'פשט: (a+b)²',                                  answers: ['a²+b²', 'a²+ab+b²', 'a²+2ab+b²', '2a+2b'],            correctIndex: 2 },
  { id: 108, difficulty: '9-10', category: 'math',    points: 1, question: 'מה האינטגרל של 2x?',                           answers: ['2', 'x²+C', '2x²+C', 'x+C'],                           correctIndex: 1 },
  { id: 109, difficulty: '9-10', category: 'math',    points: 1, question: 'כמה זה 5P2 (פרמוטציה)?',                      answers: ['10', '20', '60', '120'],                                correctIndex: 1 },
  { id: 110, difficulty: '9-10', category: 'math',    points: 1, question: 'מה ה-GCD של 48 ו-36?',                        answers: ['6', '9', '12', '18'],                                   correctIndex: 2 },
  { id: 111, difficulty: '9-10', category: 'science', points: 1, question: 'מה מספר אבוגדרו?',                             answers: ['6.02×10²¹', '6.02×10²³', '6.02×10²⁵', '6.02×10²⁷'],   correctIndex: 1 },
  { id: 112, difficulty: '9-10', category: 'science', points: 1, question: 'מה חוק ניוטון השני?',                          answers: ['F=mv', 'F=ma', 'F=m/a', 'F=m²a'],                      correctIndex: 1 },
  { id: 113, difficulty: '9-10', category: 'science', points: 1, question: 'מה הגז שנוצר בריאות שחרור?',                  answers: ['O₂', 'N₂', 'CO₂', 'H₂'],                               correctIndex: 2 },
  { id: 114, difficulty: '9-10', category: 'science', points: 1, question: 'מה סוג הקשר בין Na ל-Cl ב-NaCl?',             answers: ['קוולנטי', 'יוני', 'מטאלי', 'ואן דר ואלס'],             correctIndex: 1 },
  { id: 115, difficulty: '9-10', category: 'science', points: 1, question: 'כמה אנרגיה יש לפוטון עם תדר f? (h=קבוע פלאנק)', answers: ['hf²', 'h/f', 'hf', 'h+f'],                           correctIndex: 2 },
  { id: 116, difficulty: '9-10', category: 'science', points: 1, question: 'מהו תהליך המיטוזה?',                           answers: ['חלוקת תא ל-4', 'חלוקת תא ל-2 זהות', 'איחוד תאים', 'גדילת תא'], correctIndex: 1 },
  { id: 117, difficulty: '9-10', category: 'science', points: 1, question: 'מה הגדרת מומנט כוח?',                         answers: ['F×t', 'F×d', 'F/d', 'F×v'],                             correctIndex: 1 },
  { id: 118, difficulty: '9-10', category: 'science', points: 1, question: 'איזה חלקיק נושא מטען שלילי?',                 answers: ['פרוטון', 'נויטרון', 'אלקטרון', 'פוזיטרון'],            correctIndex: 2 },
  { id: 119, difficulty: '9-10', category: 'science', points: 1, question: 'מה הנוסחה לאנרגיה קינטית?',                   answers: ['mgh', '½mv²', 'Fd', 'mv'],                              correctIndex: 1 },
  { id: 120, difficulty: '9-10', category: 'science', points: 1, question: 'מה ה-pH של חומצה חזקה?',                      answers: ['0-2', '4-6', '7', '8-10'],                              correctIndex: 0 },

  // ===== י״א-י״ב =====
  { id: 121, difficulty: '11-12', category: 'math',    points: 1, question: 'מה הגבול: lim(x→∞) 1/x?',                    answers: ['1', '∞', '0', 'לא קיים'],                               correctIndex: 2 },
  { id: 122, difficulty: '11-12', category: 'math',    points: 1, question: 'מה הנגזרת של eˣ?',                            answers: ['eˣ⁻¹', 'eˣ', 'xeˣ', '1/eˣ'],                           correctIndex: 1 },
  { id: 123, difficulty: '11-12', category: 'math',    points: 1, question: 'מה האינטגרל ∫sin(x)dx?',                     answers: ['cos(x)+C', '-cos(x)+C', 'sin(x)+C', '-sin(x)+C'],       correctIndex: 1 },
  { id: 124, difficulty: '11-12', category: 'math',    points: 1, question: 'מה מספר ה-e בקירוב?',                         answers: ['2.14', '2.72', '3.14', '1.62'],                         correctIndex: 1 },
  { id: 125, difficulty: '11-12', category: 'math',    points: 1, question: 'כמה זה C(10,3)?',                             answers: ['30', '60', '120', '720'],                               correctIndex: 2 },
  { id: 126, difficulty: '11-12', category: 'math',    points: 1, question: 'מה ה-determinant של מטריצה [[1,2],[3,4]]?',   answers: ['-2', '2', '-1', '10'],                                  correctIndex: 0 },
  { id: 127, difficulty: '11-12', category: 'math',    points: 1, question: 'מה הנגזרת של ln(x)?',                         answers: ['ln(x)', '1/x', 'x/ln(x)', 'eˣ'],                       correctIndex: 1 },
  { id: 128, difficulty: '11-12', category: 'math',    points: 1, question: 'מה תנאי התכנסות הסדרה הגיאומטרית?',          answers: ['|q|>1', '|q|=1', '|q|<1', 'q>0'],                      correctIndex: 2 },
  { id: 129, difficulty: '11-12', category: 'math',    points: 1, question: 'מה ערך tan(45°)?',                            answers: ['0', '√3/2', '√3', '1'],                                 correctIndex: 3 },
  { id: 130, difficulty: '11-12', category: 'math',    points: 1, question: 'כמה פתרונות ל: x² = -4 ב-ℝ?',               answers: ['0', '1', '2', '4'],                                     correctIndex: 0 },
  { id: 131, difficulty: '11-12', category: 'science', points: 1, question: 'מה עקרון אי הוודאות של הייזנברג?',            answers: ['אי אפשר לדעת מיקום ומהירות במדויק בו-זמנית', 'אנרגיה לא נשמרת', 'מהירות האור קבועה', 'חומר מורכב מגלים'], correctIndex: 0 },
  { id: 132, difficulty: '11-12', category: 'science', points: 1, question: 'מה ה-Kw של מים ב-25°C?',                    answers: ['10⁻⁷', '10⁻¹⁰', '10⁻¹⁴', '10⁻²¹'],                    correctIndex: 2 },
  { id: 133, difficulty: '11-12', category: 'science', points: 1, question: 'מה חוק פאראדיי הראשון?',                     answers: ['V=IR', 'כמות החומר שמשקע שווה לזרם × זמן', 'F=qE', 'E=-dΦ/dt'], correctIndex: 1 },
  { id: 134, difficulty: '11-12', category: 'science', points: 1, question: 'מה תהליך המיוזה מייצר?',                     answers: ['תאים זהים', 'תאי מין עם חצי כרומוזומים', 'חלבונים', 'תאי גזע'], correctIndex: 1 },
  { id: 135, difficulty: '11-12', category: 'science', points: 1, question: 'מה קבוע פלאנק (h) בקירוב?',                  answers: ['6.63×10⁻³⁴ J·s', '6.63×10⁻²⁴ J·s', '9.11×10⁻³¹ kg', '1.6×10⁻¹⁹ C'], correctIndex: 0 },
  { id: 136, difficulty: '11-12', category: 'science', points: 1, question: 'מה מהירות קול באוויר בקירוב?',               answers: ['340 מ/ש', '3000 מ/ש', '30,000 מ/ש', '300 מ/ש'],          correctIndex: 0 },
  { id: 137, difficulty: '11-12', category: 'science', points: 1, question: 'מה ה-EMF?',                                  answers: ['כוח אלקטרומוטורי', 'כוח מגנטי', 'אנרגיה מגנטית', 'תדר'],  correctIndex: 0 },
  { id: 138, difficulty: '11-12', category: 'science', points: 1, question: 'מה הגדרת האנטרופיה?',                        answers: ['סדר מערכת', 'מדד לאי-סדר', 'אנרגיה פוטנציאלית', 'לחץ חלקי'], correctIndex: 1 },
  { id: 139, difficulty: '11-12', category: 'science', points: 1, question: 'מה הגן הדומיננטי?',                           answers: ['גן שמתבטא רק בהומוזיגוט', 'גן שמתבטא גם בהטרוזיגוט', 'גן רצסיבי', 'גן על כרומוזום X'], correctIndex: 1 },
  { id: 140, difficulty: '11-12', category: 'science', points: 1, question: 'מה חוק קירכהוף לזרמים (KCL)?',              answers: ['סכום הזרמים בצומת = 0', 'סכום המתחים במסלול = 0', 'V=IR', 'P=IV'], correctIndex: 0 },

  // ===== אוניברסיטה =====
  { id: 141, difficulty: 'university', category: 'math',    points: 1, question: 'מה הגבול: lim(x→0) sin(x)/x?',             answers: ['0', '∞', '1', 'לא קיים'],                                correctIndex: 2 },
  { id: 142, difficulty: 'university', category: 'math',    points: 1, question: 'מה טרנספורם פורייה של f(t)=δ(t)?',          answers: ['0', '1', 'e^jω', '1/jω'],                                correctIndex: 1 },
  { id: 143, difficulty: 'university', category: 'math',    points: 1, question: 'מה תנאי קושי-רימן לפונקציה אנליטית?',        answers: ['f רציפה', '∂u/∂x=∂v/∂y, ∂u/∂y=-∂v/∂x', 'f גזירה פעם אחת', 'f חסומה'], correctIndex: 1 },
  { id: 144, difficulty: 'university', category: 'math',    points: 1, question: 'מה האינטגרל ∫₋∞^∞ e^(-x²)dx?',              answers: ['1', 'π', '√π', '2√π'],                                  correctIndex: 2 },
  { id: 145, difficulty: 'university', category: 'math',    points: 1, question: 'מה הדטרמיננטה של מטריצת זהות 3×3?',          answers: ['0', '1', '3', '9'],                                      correctIndex: 1 },
  { id: 146, difficulty: 'university', category: 'math',    points: 1, question: 'מה מרחב אייגן?',                              answers: ['מרחב וקטורים שנשמרים בכיוון תחת טרנספורמציה', 'ליבת המטריצה', 'קבוצת ערכים עצמיים', 'מרחב הדמות'], correctIndex: 0 },
  { id: 147, difficulty: 'university', category: 'math',    points: 1, question: 'מה משפט סטוקס?',                              answers: ['∮F·dr = ∬(∇×F)·dS', '∯F·dS = ∭∇·F dV', '∂²u/∂t²=c²∇²u', 'F=ma'], correctIndex: 0 },
  { id: 148, difficulty: 'university', category: 'math',    points: 1, question: 'מה פולינום טיילור של eˣ סביב x=0?',           answers: ['1+x+x²/2+...', 'x+x²/2+...', '1-x+x²/2-...', 'x-x²/2+...'], correctIndex: 0 },
  { id: 149, difficulty: 'university', category: 'math',    points: 1, question: 'מה הגדרת הנגזרת לפי הגבול?',                  answers: ['[f(x+h)-f(x)]/h כש-h→∞', '[f(x+h)-f(x)]/h כש-h→0', 'f(x+1)-f(x)', 'f(x)/x'], correctIndex: 1 },
  { id: 150, difficulty: 'university', category: 'math',    points: 1, question: 'מה מרחב הילברט?',                              answers: ['מרחב וקטורי עם מכפלה פנימית שהוא שלם', 'קבוצת פונקציות רציפות', 'מרחב בנך', 'מרחב מטרי סופי'], correctIndex: 0 },
  { id: 151, difficulty: 'university', category: 'science', points: 1, question: 'מה מנת שרדינגר?',                              answers: ['משוואה לתנועה גלית של חלקיק קוונטי', 'עקרון אי-הוודאות', 'תיאוריית היחסות', 'חוק שימור מסה'], correctIndex: 0 },
  { id: 152, difficulty: 'university', category: 'science', points: 1, question: 'מה אפקט הול?',                                 answers: ['מתח הנוצר בחומר מוליך בשדה מגנטי', 'פליטת אלקטרונים מאור', 'פיזור אור', 'פולריזציה של גל'], correctIndex: 0 },
  { id: 153, difficulty: 'university', category: 'science', points: 1, question: 'מה משוואות מקסוול מתארות?',                   answers: ['מכניקה קלאסית', 'שדות אלקטרומגנטיים', 'תרמודינמיקה', 'מכניקת קוונטים'], correctIndex: 1 },
  { id: 154, difficulty: 'university', category: 'science', points: 1, question: 'מה הסיבה לסדר גבוה של חלבונים (quaternary)?', answers: ['קשרים קוולנטיים בין שרשראות', 'איחוד מספר שרשראות פוליפפטיד', 'קיפול שרשרת יחידה', 'רצף חומצות האמינו'], correctIndex: 1 },
  { id: 155, difficulty: 'university', category: 'science', points: 1, question: 'מה החוק השני של תרמודינמיקה?',                 answers: ['אנרגיה נשמרת', 'אנטרופיה של מערכת סגורה לא פוחתת', 'אנרגיה לא נברא', 'תמיד קיים חום שייר'], correctIndex: 1 },
  { id: 156, difficulty: 'university', category: 'science', points: 1, question: 'מה ה-Big Bang Theory טוענת?',                  answers: ['היקום קיים לנצח', 'היקום התחיל מנקודה סינגולרית', 'הכוכבים הם אש', 'הגלקסיות נוצרו מחומר אפל'], correctIndex: 1 },
  { id: 157, difficulty: 'university', category: 'science', points: 1, question: 'מה עיקרון ההכללה של פאולי?',                   answers: ['שני אלקטרונים לא יכולים לשתף את כל מספרי הקוונטום', 'אלקטרונים נמצאים במסלולים קבועים', 'האלקטרון הוא גל', 'מסת הפרוטון = מסת הנויטרון'], correctIndex: 0 },
  { id: 158, difficulty: 'university', category: 'science', points: 1, question: 'מה אפקט פוטואלקטרי?',                          answers: ['פליטת אלקטרונים מחומר עקב אור', 'פיזור פוטונים', 'ספיגת אור', 'קרינת גוף שחור'], correctIndex: 0 },
  { id: 159, difficulty: 'university', category: 'science', points: 1, question: 'מה הנוסחה לקצב ריאקציה כימית לפי ארניוס?',    answers: ['k=Ae^(-Ea/RT)', 'k=RT/Ea', 'k=A/T', 'k=e^(Ea/RT)'],    correctIndex: 0 },
  { id: 160, difficulty: 'university', category: 'science', points: 1, question: 'מה חלקיק הבוזון של היגס?',                     answers: ['הגורם לחלקיקים לקבל מסה', 'נושא הכוח האלקטרומגנטי', 'חלקיק האנטי-חומר', 'קווארק מסוג up'], correctIndex: 0 },

  // ===== גן – נוספות =====
  { id: 161, difficulty: 'gan', category: 'math',    points: 1, question: 'כמה זה 3 + 3?',              answers: ['4', '5', '6', '7'],                  correctIndex: 2 },
  { id: 162, difficulty: 'gan', category: 'math',    points: 1, question: 'כמה זה 8 - 5?',              answers: ['2', '3', '4', '5'],                  correctIndex: 1 },
  { id: 163, difficulty: 'gan', category: 'math',    points: 1, question: 'כמה זה 2 × 3?',              answers: ['4', '5', '6', '7'],                  correctIndex: 2 },
  { id: 164, difficulty: 'gan', category: 'math',    points: 1, question: 'כמה זה 10 - 7?',             answers: ['1', '2', '3', '4'],                  correctIndex: 2 },
  { id: 165, difficulty: 'gan', category: 'math',    points: 1, question: 'כמה זה 4 + 4?',              answers: ['6', '7', '8', '9'],                  correctIndex: 2 },
  { id: 166, difficulty: 'gan', category: 'science', points: 1, question: 'מה יוצא מעננים?',            answers: ['אש', 'שלג ומטר', 'עשן', 'אבק'],      correctIndex: 1 },
  { id: 167, difficulty: 'gan', category: 'science', points: 1, question: 'מה אוכל ארנבת?',             answers: ['דגים', 'גזר ועשב', 'בשר', 'אבנים'],  correctIndex: 1 },
  { id: 168, difficulty: 'gan', category: 'science', points: 1, question: 'איזה חיה נותנת חלב?',        answers: ['כלב', 'פרה', 'תרנגול', 'דג'],         correctIndex: 1 },
  { id: 169, difficulty: 'gan', category: 'science', points: 1, question: 'מה מרגישים כשקר?',           answers: ['חם', 'חמים', 'קר', 'לא מרגישים'],     correctIndex: 2 },
  { id: 170, difficulty: 'gan', category: 'science', points: 1, question: 'כמה עיניים יש לאדם?',        answers: ['1', '2', '3', '4'],                  correctIndex: 1 },

  // ===== א-ב – נוספות =====
  { id: 171, difficulty: '1-2', category: 'math',    points: 1, question: 'כמה זה 11 × 4?',             answers: ['40', '44', '48', '52'],               correctIndex: 1 },
  { id: 172, difficulty: '1-2', category: 'math',    points: 1, question: 'כמה זה 75 + 25?',            answers: ['90', '95', '100', '110'],             correctIndex: 2 },
  { id: 173, difficulty: '1-2', category: 'math',    points: 1, question: 'כמה זה 8 × 9?',              answers: ['63', '72', '81', '90'],               correctIndex: 1 },
  { id: 174, difficulty: '1-2', category: 'math',    points: 1, question: 'כמה זה 120 ÷ 6?',            answers: ['18', '20', '22', '24'],               correctIndex: 1 },
  { id: 175, difficulty: '1-2', category: 'math',    points: 1, question: 'כמה זה 5² (5 בריבוע)?',      answers: ['10', '15', '20', '25'],               correctIndex: 3 },
  { id: 176, difficulty: '1-2', category: 'science', points: 1, question: 'כמה שעות בשלושה ימים?',       answers: ['48', '60', '72', '84'],               correctIndex: 2 },
  { id: 177, difficulty: '1-2', category: 'science', points: 1, question: 'מה קורה לשמן במים?',          answers: ['נמס', 'שוקע', 'צף', 'נעלם'],          correctIndex: 2 },
  { id: 178, difficulty: '1-2', category: 'science', points: 1, question: 'מאיזה כיוון זורחת השמש?',     answers: ['מערב', 'צפון', 'דרום', 'מזרח'],       correctIndex: 3 },
  { id: 179, difficulty: '1-2', category: 'science', points: 1, question: 'מה החלק של הצמח שבאדמה?',    answers: ['גבעול', 'עלה', 'שורש', 'פרח'],        correctIndex: 2 },
  { id: 180, difficulty: '1-2', category: 'science', points: 1, question: 'מי ממציא הטלפון?',            answers: ['אדיסון', 'גרהם בל', 'ניוטון', 'איינשטיין'], correctIndex: 1 },

  // ===== ג-ד – נוספות =====
  { id: 181, difficulty: '3-4', category: 'math',    points: 1, question: 'כמה זה 15 × 15?',            answers: ['175', '200', '225', '250'],           correctIndex: 2 },
  { id: 182, difficulty: '3-4', category: 'math',    points: 1, question: 'מה שטח ריבוע עם צלע 9?',     answers: ['36', '54', '72', '81'],               correctIndex: 3 },
  { id: 183, difficulty: '3-4', category: 'math',    points: 1, question: 'כמה זה 5/8 + 3/8?',          answers: ['1/2', '3/4', '1', '8/16'],            correctIndex: 2 },
  { id: 184, difficulty: '3-4', category: 'math',    points: 1, question: 'כמה זה 2.5 × 4?',            answers: ['8', '10', '12', '14'],                correctIndex: 1 },
  { id: 185, difficulty: '3-4', category: 'math',    points: 1, question: 'כמה אלפים ב-45,000?',         answers: ['4', '5', '45', '450'],                correctIndex: 2 },
  { id: 186, difficulty: '3-4', category: 'science', points: 1, question: 'מה גרם לכחדת הדינוזאורים?',  answers: ['הצפה', 'אסטרואיד', 'מחלה', 'צינה'],  correctIndex: 1 },
  { id: 187, difficulty: '3-4', category: 'science', points: 1, question: 'כמה שנים בעידן יולי?',        answers: ['365', '100', '1000', '365.25'],       correctIndex: 3 },
  { id: 188, difficulty: '3-4', category: 'science', points: 1, question: 'מה הפלנטה הגדולה ביותר?',    answers: ['שבתאי', 'נפטון', 'צדק', 'אורנוס'],   correctIndex: 2 },
  { id: 189, difficulty: '3-4', category: 'science', points: 1, question: 'מה ה-DNA מקודד?',             answers: ['אנרגיה', 'חלבונים', 'שומנים', 'מים'], correctIndex: 1 },
  { id: 190, difficulty: '3-4', category: 'science', points: 1, question: 'מה סוג הגל של רעידת אדמה?',  answers: ['גל אור', 'גל מכני', 'גל רדיו', 'גל חום'], correctIndex: 1 },

  // ===== ה-ו – נוספות =====
  { id: 191, difficulty: '5-6', category: 'math',    points: 1, question: 'פתור: 3x - 7 = 14',           answers: ['5', '6', '7', '8'],                  correctIndex: 2 },
  { id: 192, difficulty: '5-6', category: 'math',    points: 1, question: 'כמה זה 3/4 × 8/9?',          answers: ['1/3', '2/3', '1', '4/3'],             correctIndex: 1 },
  { id: 193, difficulty: '5-6', category: 'math',    points: 1, question: 'כמה זה 12²?',                 answers: ['124', '132', '144', '156'],           correctIndex: 2 },
  { id: 194, difficulty: '5-6', category: 'math',    points: 1, question: 'מה אחוז הרווח: קנה ב-80 מכר ב-100?', answers: ['15%', '20%', '25%', '30%'],  correctIndex: 2 },
  { id: 195, difficulty: '5-6', category: 'math',    points: 1, question: 'כמה זה 5/6 ÷ 5/3?',           answers: ['1/2', '2/3', '1', '5/6'],             correctIndex: 0 },
  { id: 196, difficulty: '5-6', category: 'science', points: 1, question: 'מה הצורה הכימית של מלח?',    answers: ['KCl', 'NaCl', 'CaCl₂', 'MgCl₂'],     correctIndex: 1 },
  { id: 197, difficulty: '5-6', category: 'science', points: 1, question: 'כמה ורידים יוצאים מהלב?',    answers: ['1', '2', '3', '4'],                   correctIndex: 1 },
  { id: 198, difficulty: '5-6', category: 'science', points: 1, question: 'מה קצב הלב התקין לאדם?',     answers: ['40-50', '60-100', '120-140', '150+'], correctIndex: 1 },
  { id: 199, difficulty: '5-6', category: 'science', points: 1, question: 'מה הכוח שמושך גופים לאדמה?', answers: ['מגנטיות', 'חשמל', 'גרביטציה', 'לחץ'], correctIndex: 2 },
  { id: 200, difficulty: '5-6', category: 'science', points: 1, question: 'מה צבעי הקשת בסדר?',         answers: ['אדום כתום צהוב ירוק כחול סגול', 'כחול ירוק צהוב כתום אדום סגול', 'סגול כחול ירוק צהוב כתום אדום', 'אדום כתום צהוב כחול ירוק סגול'], correctIndex: 0 },

  // ===== ז-ח – נוספות =====
  { id: 201, difficulty: '7-8', category: 'math',    points: 1, question: 'פתור: 5x + 3 = 28',          answers: ['4', '5', '6', '7'],                  correctIndex: 1 },
  { id: 202, difficulty: '7-8', category: 'math',    points: 1, question: 'כמה זה (2³)² ?',              answers: ['32', '64', '128', '256'],             correctIndex: 1 },
  { id: 203, difficulty: '7-8', category: 'math',    points: 1, question: 'מה הזווית החיצונית של משושה?', answers: ['45°', '60°', '72°', '90°'],          correctIndex: 1 },
  { id: 204, difficulty: '7-8', category: 'math',    points: 1, question: 'פשט: 3(2x-4)+6',              answers: ['6x-6', '6x-12', '6x+6', '6x'],       correctIndex: 0 },
  { id: 205, difficulty: '7-8', category: 'math',    points: 1, question: 'כמה זה |−15|?',               answers: ['-15', '0', '15', '150'],              correctIndex: 2 },
  { id: 206, difficulty: '7-8', category: 'science', points: 1, question: 'מה הסמל הכימי של כלור?',      answers: ['C', 'Ca', 'Cl', 'Co'],                correctIndex: 2 },
  { id: 207, difficulty: '7-8', category: 'science', points: 1, question: 'כמה חוליות יש בעמוד השדרה?', answers: ['24', '33', '36', '42'],               correctIndex: 1 },
  { id: 208, difficulty: '7-8', category: 'science', points: 1, question: 'מה תפקיד הכליות?',            answers: ['עיכול', 'סינון דם ויצירת שתן', 'נשימה', 'ייצור הורמונים'], correctIndex: 1 },
  { id: 209, difficulty: '7-8', category: 'science', points: 1, question: 'מה היחידה למדידת תדר?',       answers: ['וולט', 'אמפר', 'הרץ', 'ואט'],         correctIndex: 2 },
  { id: 210, difficulty: '7-8', category: 'science', points: 1, question: 'מה מהירות קול במים?',         answers: ['340 מ/ש', '750 מ/ש', '1500 מ/ש', '3000 מ/ש'], correctIndex: 2 },

  // ===== ט-י – נוספות =====
  { id: 211, difficulty: '9-10', category: 'math',    points: 1, question: 'מה הנגזרת של sin(x)?',       answers: ['-sin(x)', 'cos(x)', '-cos(x)', 'tan(x)'], correctIndex: 1 },
  { id: 212, difficulty: '9-10', category: 'math',    points: 1, question: 'כמה זה C(6,2)?',             answers: ['12', '15', '18', '30'],               correctIndex: 1 },
  { id: 213, difficulty: '9-10', category: 'math',    points: 1, question: 'מה גבול: lim(x→2) (x²-4)/(x-2)?', answers: ['0', '2', '4', '∞'],             correctIndex: 2 },
  { id: 214, difficulty: '9-10', category: 'math',    points: 1, question: 'כמה זה sin²x + cos²x?',      answers: ['0', '0.5', '1', '2'],                 correctIndex: 2 },
  { id: 215, difficulty: '9-10', category: 'math',    points: 1, question: 'מה סכום זוויות המצולע בעל 8 צלעות?', answers: ['900°', '1080°', '1260°', '1440°'], correctIndex: 1 },
  { id: 216, difficulty: '9-10', category: 'science', points: 1, question: 'מה אורך גל האור הנראה?',     answers: ['1-10 נמ', '400-700 נמ', '1-10 מ"מ', '1-100 מ'], correctIndex: 1 },
  { id: 217, difficulty: '9-10', category: 'science', points: 1, question: 'מה תפקיד הריבוזום?',         answers: ['שכפול DNA', 'סינתזת חלבונים', 'ייצור ATP', 'פירוק פסולת'], correctIndex: 1 },
  { id: 218, difficulty: '9-10', category: 'science', points: 1, question: 'מה חוק שימור התנע?',         answers: ['p=mv תמיד קבוע', 'בהיעדר כוח חיצוני תנע מערכת סגורה קבוע', 'F=ma', 'E=mc²'], correctIndex: 1 },
  { id: 219, difficulty: '9-10', category: 'science', points: 1, question: 'מה ה-ATP?',                  answers: ['חומצת שומן', 'מולקולת אנרגיה תאית', 'חלבון', 'ורמה גנטית'], correctIndex: 1 },
  { id: 220, difficulty: '9-10', category: 'science', points: 1, question: 'מה עיקרון ארכימדס?',         answers: ['גוף שקוע דוחה נוזל שווה למסתו', 'גוף שקוע דוחה נוזל שווה לנפחו', 'כל גוף צף', 'לחץ = כוח × שטח'], correctIndex: 1 },

  // ===== י״א-י״ב – נוספות =====
  { id: 221, difficulty: '11-12', category: 'math',    points: 1, question: 'מה ∫x²dx?',                answers: ['x³+C', 'x³/3+C', '2x+C', '3x³+C'],   correctIndex: 1 },
  { id: 222, difficulty: '11-12', category: 'math',    points: 1, question: 'מה נגזרת tan(x)?',          answers: ['sin(x)/cos(x)', '1/cos²x', '-1/sin²x', 'cos²x'], correctIndex: 1 },
  { id: 223, difficulty: '11-12', category: 'math',    points: 1, question: 'כמה פתרונות ל-|2x-1|=5?',  answers: ['0', '1', '2', '3'],                   correctIndex: 2 },
  { id: 224, difficulty: '11-12', category: 'math',    points: 1, question: 'מה קיים בכל חוג אבלי?',     answers: ['אידמפוטנט', 'איבר ניטרלי', 'מחלקת מנה', 'מרחב וקטורי'], correctIndex: 1 },
  { id: 225, difficulty: '11-12', category: 'math',    points: 1, question: 'כמה אסימפטוטות אנכיות ל- 1/(x²-1)?', answers: ['0', '1', '2', '3'],          correctIndex: 2 },
  { id: 226, difficulty: '11-12', category: 'science', points: 1, question: 'מה עקרון לה שאטלייה?',      answers: ['מערכת בשיווי משקל מגיבה לשינוי כדי לנטרל אותו', 'אנרגיה מתחלקת שווה', 'אנטרופיה עולה', 'מהירות תגובה פרופורציונלית לריכוז'], correctIndex: 0 },
  { id: 227, difficulty: '11-12', category: 'science', points: 1, question: 'מה הקשר בין מתח לשדה חשמלי?', answers: ['E=V/d', 'E=Vd', 'V=Ed²', 'E=V²'], correctIndex: 0 },
  { id: 228, difficulty: '11-12', category: 'science', points: 1, question: 'מה תהליך הטרנסקריפציה?',   answers: ['העתקת DNA ל-RNA', 'תרגום RNA לחלבון', 'שכפול DNA', 'פירוק חלבון'], correctIndex: 0 },
  { id: 229, difficulty: '11-12', category: 'science', points: 1, question: 'מה המשוואה הכללית לגז אידיאלי?', answers: ['PV=nRT', 'PV=RT', 'P=nRT', 'PV=nR'], correctIndex: 0 },
  { id: 230, difficulty: '11-12', category: 'science', points: 1, question: 'מה המטען של האלקטרון?',     answers: ['0', '+1.6×10⁻¹⁹ C', '-1.6×10⁻¹⁹ C', '9.1×10⁻³¹ C'], correctIndex: 2 },

  // ===== אוניברסיטה – נוספות =====
  { id: 231, difficulty: 'university', category: 'math',    points: 1, question: 'מה משפט פרמה הגדול?',  answers: ['xⁿ+yⁿ=zⁿ אין פתרונות שלמים לn>2', 'כל מספר ראשוני הוא אי-זוגי', 'π אי-רציונלי', 'e טרנסצנדנטי'], correctIndex: 0 },
  { id: 232, difficulty: 'university', category: 'math',    points: 1, question: 'מה הגדרת מרחב טופולוגי?', answers: ['קבוצה עם פונקציית מטריקה', 'קבוצה עם אוסף של קבוצות פתוחות הקיימות בתנאים', 'מרחב עם מכפלה פנימית', 'מרחב בנך'], correctIndex: 1 },
  { id: 233, difficulty: 'university', category: 'math',    points: 1, question: 'מה משפט גאוס (דיברגנס)?', answers: ['∯F·dS=∭∇·F dV', '∮F·dr=∬(∇×F)·dS', '∫∫∫f dV=∫∫f dA', 'F=ma'], correctIndex: 0 },
  { id: 234, difficulty: 'university', category: 'math',    points: 1, question: 'מה התנאי לרצף פונקציה b-ב?', answers: ['lim(x→b) f(x)=f(b)', 'f גזירה ב-b', 'f חסומה', 'f מונוטונית'], correctIndex: 0 },
  { id: 235, difficulty: 'university', category: 'math',    points: 1, question: 'מה משפט המדד האפסי?',   answers: ['קבוצה בת-מנייה היא באפס מדד לבג', 'כל קבוצה פתוחה ניתנת למדידה', 'המדד של ℝ הוא אחד', 'כל סדרה מתכנסת'], correctIndex: 0 },
  { id: 236, difficulty: 'university', category: 'science', points: 1, question: 'מה תיאוריית הסטרינגים מציעה?', answers: ['החלקיקים הם חוטים רוטטים חד-ממדיים', 'הגלים הם חלקיקים', 'המרחב הוא דיסקרטי', 'הכוח החזק הוא אינסופי'], correctIndex: 0 },
  { id: 237, difficulty: 'university', category: 'science', points: 1, question: 'מה עקרון כוורות?',      answers: ['חישוב אנרגיה קינטית', 'שיטה לחישוב ספקטרום', 'עיקרון וריאציוני לאנרגיה בסיס', 'חוק שימור'], correctIndex: 2 },
  { id: 238, difficulty: 'university', category: 'science', points: 1, question: 'מה ה-Renormalization Group?', answers: ['שיטה לניתוח מערכות בסקאלות שונות', 'חישוב מסת חלקיקים', 'תיאוריה של גלים', 'שיטת אינטגרציה'], correctIndex: 0 },
  { id: 239, difficulty: 'university', category: 'science', points: 1, question: 'מה הנוסחה לאנרגיה חופשית של גיבס?', answers: ['G=H+TS', 'G=H-TS', 'G=U+PV', 'G=kT ln Z'], correctIndex: 1 },
  { id: 240, difficulty: 'university', category: 'science', points: 1, question: 'מה הגדרת הסופרקונדוקטיביות?', answers: ['התנגדות חשמלית אפסית מתחת לטמפרטורה קריטית', 'הולכה מושלמת של חום', 'פליטת אור קוהרנטי', 'הזרמת חשמל ללא חיכוך'], correctIndex: 0 },

  // ===== עברית – גן (קריאה ואותיות) =====
  { id: 241, difficulty: 'gan', category: 'hebrew', points: 1, question: 'באיזו אות מתחילה המילה "אמא"?',             answers: ['ב', 'א', 'מ', 'ע'],                           correctIndex: 1 },
  { id: 242, difficulty: 'gan', category: 'hebrew', points: 1, question: 'כמה אותיות במילה "ילד"?',                   answers: ['2', '3', '4', '5'],                           correctIndex: 1 },
  { id: 243, difficulty: 'gan', category: 'hebrew', points: 1, question: 'איזו אות זו? "ש"',                          answers: ['ס', 'ש', 'צ', 'ז'],                           correctIndex: 1 },
  { id: 244, difficulty: 'gan', category: 'hebrew', points: 1, question: 'באיזו אות מסתיימת המילה "כלב"?',            answers: ['כ', 'ל', 'ב', 'ד'],                           correctIndex: 2 },
  { id: 245, difficulty: 'gan', category: 'hebrew', points: 1, question: 'מה הצליל של האות "מ"?',                    answers: ['נ', 'מ', 'ב', 'פ'],                           correctIndex: 1 },
  { id: 246, difficulty: 'gan', category: 'hebrew', points: 1, question: 'איזו מילה מתחילה באות "ד"?',               answers: ['כלב', 'דג', 'ספר', 'עץ'],                     correctIndex: 1 },
  { id: 247, difficulty: 'gan', category: 'hebrew', points: 1, question: 'כמה אותיות במילה "שמש"?',                  answers: ['2', '3', '4', '5'],                           correctIndex: 1 },
  { id: 248, difficulty: 'gan', category: 'hebrew', points: 1, question: 'באיזו אות מתחילה המילה "בית"?',            answers: ['ב', 'י', 'ת', 'ד'],                           correctIndex: 0 },
  { id: 249, difficulty: 'gan', category: 'hebrew', points: 1, question: 'איזו מילה מתחילה באות "ע"?',               answers: ['אפר', 'עץ', 'יום', 'חול'],                    correctIndex: 1 },
  { id: 250, difficulty: 'gan', category: 'hebrew', points: 1, question: 'מה הצליל של האות "ר"?',                    answers: ['ל', 'נ', 'ר', 'ד'],                           correctIndex: 2 },
  { id: 251, difficulty: 'gan', category: 'hebrew', points: 1, question: 'איזו אות זו? "ל"',                          answers: ['כ', 'ל', 'ח', 'ן'],                           correctIndex: 1 },
  { id: 252, difficulty: 'gan', category: 'hebrew', points: 1, question: 'כמה אותיות במילה "אב"?',                   answers: ['1', '2', '3', '4'],                           correctIndex: 1 },
  { id: 253, difficulty: 'gan', category: 'hebrew', points: 1, question: 'איזו מילה מתחילה באות "ח"?',               answers: ['דוב', 'חתול', 'פרח', 'ספר'],                  correctIndex: 1 },
  { id: 254, difficulty: 'gan', category: 'hebrew', points: 1, question: 'באיזו אות מסתיימת המילה "שמש"?',           answers: ['ש', 'מ', 'ס', 'ן'],                           correctIndex: 0 },
  { id: 255, difficulty: 'gan', category: 'hebrew', points: 1, question: 'איזו אות זו? "פ"',                          answers: ['ב', 'כ', 'פ', 'ד'],                           correctIndex: 2 },
  { id: 256, difficulty: 'gan', category: 'hebrew', points: 1, question: 'מה ההפך של "גדול"?',                       answers: ['יפה', 'קטן', 'מהיר', 'חם'],                   correctIndex: 1 },
  { id: 257, difficulty: 'gan', category: 'hebrew', points: 1, question: 'איזו מילה מסמנת צבע?',                     answers: ['כלב', 'ילד', 'אדום', 'בית'],                  correctIndex: 2 },
  { id: 258, difficulty: 'gan', category: 'hebrew', points: 1, question: 'איזו מילה מסמנת בעל חיים?',                answers: ['שולחן', 'חתול', 'כיסא', 'ספר'],               correctIndex: 1 },
  { id: 259, difficulty: 'gan', category: 'hebrew', points: 1, question: 'באיזו אות מתחילה המילה "ירח"?',            answers: ['א', 'ו', 'י', 'ח'],                           correctIndex: 2 },
  { id: 260, difficulty: 'gan', category: 'hebrew', points: 1, question: 'כמה אותיות במילה "תפוח"?',                 answers: ['3', '4', '5', '6'],                           correctIndex: 1 },

  // ===== עברית – א-ב (קריאה בסיסית) =====
  { id: 261, difficulty: '1-2', category: 'hebrew', points: 1, question: 'מה ההפך של "חם"?',                         answers: ['יפה', 'קר', 'מהיר', 'גדול'],                  correctIndex: 1 },
  { id: 262, difficulty: '1-2', category: 'hebrew', points: 1, question: 'איזו מילה היא שם עצם?',                    answers: ['יפה', 'רץ', 'כלב', 'אדום'],                   correctIndex: 2 },
  { id: 263, difficulty: '1-2', category: 'hebrew', points: 1, question: 'השלם: "הילד ___ לבית הספר"',               answers: ['הלכה', 'הלך', 'הלכו', 'ללכת'],                correctIndex: 1 },
  { id: 264, difficulty: '1-2', category: 'hebrew', points: 1, question: 'מה ריבוי של "כלב"?',                       answers: ['כלבה', 'כלבים', 'כלבות', 'כלבן'],             correctIndex: 1 },
  { id: 265, difficulty: '1-2', category: 'hebrew', points: 1, question: 'איזו מילה היא פועל?',                       answers: ['שמש', 'ספר', 'רץ', 'ילד'],                    correctIndex: 2 },
  { id: 266, difficulty: '1-2', category: 'hebrew', points: 1, question: 'מה נקבת "ילד"?',                           answers: ['ילדות', 'ילדה', 'ילדים', 'ילדן'],             correctIndex: 1 },
  { id: 267, difficulty: '1-2', category: 'hebrew', points: 1, question: 'השלם: "הילדה ___ בגן"',                    answers: ['שיחקה', 'שיחק', 'שיחקו', 'שיחקת'],           correctIndex: 0 },
  { id: 268, difficulty: '1-2', category: 'hebrew', points: 1, question: 'מה ריבוי של "ספר"?',                       answers: ['ספרות', 'ספרים', 'ספרן', 'ספרה'],             correctIndex: 1 },
  { id: 269, difficulty: '1-2', category: 'hebrew', points: 1, question: 'מה ההפך של "קצר"?',                        answers: ['רחב', 'גבוה', 'ארוך', 'עגול'],                correctIndex: 2 },
  { id: 270, difficulty: '1-2', category: 'hebrew', points: 1, question: 'איזו מילה היא תואר?',                       answers: ['חתול', 'רץ', 'יפה', 'בית'],                   correctIndex: 2 },
  { id: 271, difficulty: '1-2', category: 'hebrew', points: 1, question: 'מה נקבת "מורה" (זכר)?',                    answers: ['מורות', 'מורה (נקבה)', 'מורית', 'מוריה'],     correctIndex: 1 },
  { id: 272, difficulty: '1-2', category: 'hebrew', points: 1, question: 'השלם: "אני ___ לבית" (הווה)',              answers: ['הלכתי', 'הולך/ת', 'ילך', 'לכת'],              correctIndex: 1 },
  { id: 273, difficulty: '1-2', category: 'hebrew', points: 1, question: 'מה ריבוי של "עץ"?',                        answers: ['עצות', 'עצים', 'עצן', 'עצות'],               correctIndex: 1 },
  { id: 274, difficulty: '1-2', category: 'hebrew', points: 1, question: 'מה ההפך של "מהר"?',                        answers: ['יפה', 'לאט', 'קצר', 'קל'],                    correctIndex: 1 },
  { id: 275, difficulty: '1-2', category: 'hebrew', points: 1, question: 'איזו מילה היא שם פרטי?',                   answers: ['ילד', 'בית', 'דוד', 'כלב'],                   correctIndex: 2 },
  { id: 276, difficulty: '1-2', category: 'hebrew', points: 1, question: 'מה ריבוי של "שולחן"?',                     answers: ['שולחנות', 'שולחנים', 'שולחנן', 'שולחני'],    correctIndex: 0 },
  { id: 277, difficulty: '1-2', category: 'hebrew', points: 1, question: 'השלם: "הם ___ בגינה" (עבר)',               answers: ['שיחק', 'שיחקה', 'שיחקו', 'שיחקת'],           correctIndex: 2 },
  { id: 278, difficulty: '1-2', category: 'hebrew', points: 1, question: 'מה נקבה רבים של "ילד"?',                   answers: ['ילדות', 'ילדים', 'ילדה', 'ילדן'],             correctIndex: 0 },
  { id: 279, difficulty: '1-2', category: 'hebrew', points: 1, question: 'מה ההפך של "כבד"?',                        answers: ['גדול', 'קל', 'גבוה', 'רחב'],                  correctIndex: 1 },
  { id: 280, difficulty: '1-2', category: 'hebrew', points: 1, question: 'איזו מילה כתובה נכון?',                    answers: ['אכל', 'אחל', 'אגל', 'אכלה → "אכלה"'],         correctIndex: 0 },

  // ===== עברית – ג-ד (קריאה ודקדוק) =====
  { id: 281, difficulty: '3-4', category: 'hebrew', points: 1, question: 'מה שורש המילה "כתיבה"?',                   answers: ['כות', 'כתב', 'כתי', 'תכב'],                   correctIndex: 1 },
  { id: 282, difficulty: '3-4', category: 'hebrew', points: 1, question: 'איזו מילה בניין פיעל?',                     answers: ['כתב', 'כיתב', 'נכתב', 'הכתיב'],              correctIndex: 1 },
  { id: 283, difficulty: '3-4', category: 'hebrew', points: 1, question: 'מה מין המילה "שמש"?',                      answers: ['זכר', 'נקבה', 'שניהם', 'אין מין'],            correctIndex: 2 },
  { id: 284, difficulty: '3-4', category: 'hebrew', points: 1, question: 'מה שורש המילה "לימוד"?',                   answers: ['ליד', 'למד', 'לומ', 'מדל'],                   correctIndex: 1 },
  { id: 285, difficulty: '3-4', category: 'hebrew', points: 1, question: 'השלם: "הילד ___ את השיעור" (עבר)',         answers: ['למד', 'לומד', 'ילמד', 'ללמוד'],               correctIndex: 0 },
  { id: 286, difficulty: '3-4', category: 'hebrew', points: 1, question: 'מה הסמיכות של "בית + ספר"?',              answers: ['בית-ספר', 'ספר הבית', 'בית הספר', 'ספרבית'], correctIndex: 2 },
  { id: 287, difficulty: '3-4', category: 'hebrew', points: 1, question: 'מה בניין קל (פעל) בהווה לגוף שלישי זכר?', answers: ['כותב', 'מכתיב', 'נכתב', 'התכתב'],             correctIndex: 0 },
  { id: 288, difficulty: '3-4', category: 'hebrew', points: 1, question: 'מה שורש המילה "שמירה"?',                   answers: ['שמח', 'שמר', 'שים', 'מרש'],                   correctIndex: 1 },
  { id: 289, difficulty: '3-4', category: 'hebrew', points: 1, question: 'איזו מילה היא תואר הפועל?',                answers: ['מהר', 'מהיר', 'מהירות', 'להמהר'],             correctIndex: 0 },
  { id: 290, difficulty: '3-4', category: 'hebrew', points: 1, question: 'מה ריבוי של "גג"?',                        answers: ['גגים', 'גגות', 'גגן', 'גגות ←"גגות"'],        correctIndex: 0 },
  { id: 291, difficulty: '3-4', category: 'hebrew', points: 1, question: 'השלם: "היא תלמידה ___" (חכמה/חכם)',        answers: ['חכמה', 'חכם', 'חכמים', 'חכמות'],              correctIndex: 0 },
  { id: 292, difficulty: '3-4', category: 'hebrew', points: 1, question: 'מה שורש המילה "הכנה"?',                   answers: ['הכן', 'כנה', 'כון', 'הכנ'],                   correctIndex: 2 },
  { id: 293, difficulty: '3-4', category: 'hebrew', points: 1, question: 'איזו מילה בבניין נפעל?',                   answers: ['כתב', 'כיתב', 'נכתב', 'הכתיב'],              correctIndex: 2 },
  { id: 294, difficulty: '3-4', category: 'hebrew', points: 1, question: 'מה הנגזרת של "ספר" (פעולה)?',             answers: ['ספרות', 'ספרן', 'ספירה', 'ספרייה'],           correctIndex: 2 },
  { id: 295, difficulty: '3-4', category: 'hebrew', points: 1, question: 'מה צורת הציווי של "ללכת" (אתה)?',         answers: ['לך', 'הלך', 'ילך', 'לכת'],                    correctIndex: 0 },
  { id: 296, difficulty: '3-4', category: 'hebrew', points: 1, question: 'מה ההגדרה של "נרדף"?',                    answers: ['מילה שנרדפה', 'מילה בעלת משמעות דומה', 'מילה הפוכה', 'מילה ממקור זר'], correctIndex: 1 },
  { id: 297, difficulty: '3-4', category: 'hebrew', points: 1, question: 'מה שורש המילה "מגורים"?',                 answers: ['מגר', 'גור', 'גרם', 'מרג'],                   correctIndex: 1 },
  { id: 298, difficulty: '3-4', category: 'hebrew', points: 1, question: 'השלם: "הם ___ לבית הספר מחר" (עתיד)',     answers: ['הלכו', 'הולכים', 'ילכו', 'לכו'],              correctIndex: 2 },
  { id: 299, difficulty: '3-4', category: 'hebrew', points: 1, question: 'מה בניין הפעיל?',                          answers: ['כתב', 'כיתב', 'נכתב', 'הכתיב'],              correctIndex: 3 },
  { id: 300, difficulty: '3-4', category: 'hebrew', points: 1, question: 'מה סימן הרבים הנפוץ לנקבה?',              answers: ['ים-', 'ות-', 'ן-', 'ית-'],                    correctIndex: 1 },

  // ===== עברית – ה-ו (הבנת הנקרא) =====
  { id: 301, difficulty: '5-6', category: 'hebrew', points: 1, question: '"הנחש היה ערום מכל חית השדה." מה המילה "ערום" מסמלת כאן?', answers: ['עירום', 'חכם ומתוחכם', 'מהיר', 'יפה'],        correctIndex: 1 },
  { id: 302, difficulty: '5-6', category: 'hebrew', points: 1, question: 'מה הכלי הספרותי בביטוי "הלילה שחור כפחם"?', answers: ['אנפורה', 'השוואה (דמוי)', 'גוזמה', 'אירוניה'], correctIndex: 1 },
  { id: 303, difficulty: '5-6', category: 'hebrew', points: 1, question: 'מה הוא "מספר בכל יודע"?',                 answers: ['גיבור הסיפור', 'מספר שיודע הכל על הדמויות', 'קורא הסיפור', 'המחבר'], correctIndex: 1 },
  { id: 304, difficulty: '5-6', category: 'hebrew', points: 1, question: 'מה פירוש "פרסונה" בספרות?',               answers: ['גיבור שלילי', 'הדמות שמאחורי המחבר', 'מספר', 'סיפור מסגרת'], correctIndex: 1 },
  { id: 305, difficulty: '5-6', category: 'hebrew', points: 1, question: '"הים געה." מה הכלי הספרותי?',             answers: ['דמוי', 'גוזמה', 'אנימיזם', 'אנפורה'],         correctIndex: 2 },
  { id: 306, difficulty: '5-6', category: 'hebrew', points: 1, question: 'מה ההבדל בין עלילה לנושא?',               answers: ['עלילה=מה קורה, נושא=הרעיון המרכזי', 'נושא=מה קורה, עלילה=הרעיון', 'שניהם זהים', 'עלילה=הדמויות'], correctIndex: 0 },
  { id: 307, difficulty: '5-6', category: 'hebrew', points: 1, question: 'מה כינוי גוף "הם" בעברית?',               answers: ['גוף ראשון רבים', 'גוף שני רבים', 'גוף שלישי רבים זכר', 'גוף שלישי יחיד'], correctIndex: 2 },
  { id: 308, difficulty: '5-6', category: 'hebrew', points: 1, question: 'מה "אירוניה" בספרות?',                    answers: ['תיאור יפה', 'אמירה שמשמעה ההפך ממה שנאמר', 'חזרה על מילה', 'השוואה'], correctIndex: 1 },
  { id: 309, difficulty: '5-6', category: 'hebrew', points: 1, question: 'מה שורש המילה "הסתכלות"?',               answers: ['הסת', 'סכל', 'כלת', 'סכן'],                   correctIndex: 1 },
  { id: 310, difficulty: '5-6', category: 'hebrew', points: 1, question: 'מה בניין המילה "הסתכל"?',                 answers: ['פעל', 'פיעל', 'הפעיל', 'התפעל'],              correctIndex: 3 },
  { id: 311, difficulty: '5-6', category: 'hebrew', points: 1, question: '"חץ עבר בין עיניו." מה הכוונה?',           answers: ['חץ אמיתי עבר', 'מבט חד וקשה', 'הוא עיוור', 'הוא ירה'],  correctIndex: 1 },
  { id: 312, difficulty: '5-6', category: 'hebrew', points: 1, question: 'מה "פרולוג" בטקסט?',                      answers: ['פרק אחרון', 'הקדמה לסיפור', 'שיא העלילה', 'הסיום'],   correctIndex: 1 },
  { id: 313, difficulty: '5-6', category: 'hebrew', points: 1, question: 'מה ההבדל בין "קנאה" ל"קינאה"?',          answers: ['אין הבדל', 'קנאה=צמח, קינאה=רגש', 'קנאה=קנייה, קינאה=שירת אבל', 'שניהם שגויים'], correctIndex: 2 },
  { id: 314, difficulty: '5-6', category: 'hebrew', points: 1, question: 'מה "הדמות הראשית"?',                      answers: ['מספר', 'הגיבור המרכזי שסביבו הסיפור', 'הנבל', 'המחבר'], correctIndex: 1 },
  { id: 315, difficulty: '5-6', category: 'hebrew', points: 1, question: 'מה "גוזמה" (היפרבולה)?',                  answers: ['השוואה', 'הגזמה קיצונית לצרכי דגש', 'אנימיזם', 'חזרה'],  correctIndex: 1 },
  { id: 316, difficulty: '5-6', category: 'hebrew', points: 1, question: 'מה פירוש "דיאלוג"?',                      answers: ['תיאור סצנה', 'שיח בין דמויות', 'מונולוג פנימי', 'תיאור מקום'], correctIndex: 1 },
  { id: 317, difficulty: '5-6', category: 'hebrew', points: 1, question: 'מה "מבנה כיאסטי"?',                       answers: ['חזרה על מילים', 'A-B-B-A מבנה סימטרי הפוך', 'שורות שוות', 'חרוז'], correctIndex: 1 },
  { id: 318, difficulty: '5-6', category: 'hebrew', points: 1, question: 'מה "שיא העלילה" (קלימקס)?',               answers: ['תחילת הסיפור', 'נקודת המתח הגבוהה ביותר', 'הסיום', 'הרקע'],  correctIndex: 1 },
  { id: 319, difficulty: '5-6', category: 'hebrew', points: 1, question: 'מה ההבדל בין "שיר" ל"פרוזה"?',           answers: ['שיר=מחורז, פרוזה=לא', 'שיר מחולק לשורות ועשוי להיות מחורז, פרוזה=כתיבה רגילה', 'אין הבדל', 'שיר=קצר יותר'], correctIndex: 1 },
  { id: 320, difficulty: '5-6', category: 'hebrew', points: 1, question: 'מה "אלגוריה"?',                            answers: ['סיפור עם משמעות נסתרת', 'שיר אהבה', 'מחזה', 'סיפור ילדים'], correctIndex: 0 },

  // ===== עברית – ז-ח (הבנת הנקרא) =====
  { id: 321, difficulty: '7-8', category: 'hebrew', points: 1, question: 'מה "פסוק" בשירה?',                         answers: ['כל השיר', 'קבוצת שורות המהוות יחידה', 'שורה אחת', 'הכותרת'], correctIndex: 1 },
  { id: 322, difficulty: '7-8', category: 'hebrew', points: 1, question: 'מה ההבדל בין "סיפורת" ל"עובדה"?',         answers: ['סיפורת=קצרה, עובדה=ארוכה', 'סיפורת=בדיה, עובדה=מציאות', 'אין הבדל', 'סיפורת=שירה'], correctIndex: 1 },
  { id: 323, difficulty: '7-8', category: 'hebrew', points: 1, question: 'מה "מונולוג פנימי"?',                      answers: ['שיח בין דמויות', 'מחשבות הדמות שנחשפות לקורא', 'תיאור נוף', 'מספר חיצוני'], correctIndex: 1 },
  { id: 324, difficulty: '7-8', category: 'hebrew', points: 1, question: 'מה "אנאפורה"?',                            answers: ['השוואה', 'חזרה על מילה/ביטוי בתחילת שורות', 'גוזמה', 'דמוי'], correctIndex: 1 },
  { id: 325, difficulty: '7-8', category: 'hebrew', points: 1, question: '"לא שמע ולא ראה." מה הכלי הספרותי?',      answers: ['ניגוד', 'מבנה מקבילי', 'גוזמה', 'אנפורה'],    correctIndex: 1 },
  { id: 326, difficulty: '7-8', category: 'hebrew', points: 1, question: 'מה "נקודת מבט גוף ראשון"?',               answers: ['המספר מחוץ לסיפור', 'הגיבור עצמו מספר', 'כל יודע', 'מספר אנונימי'], correctIndex: 1 },
  { id: 327, difficulty: '7-8', category: 'hebrew', points: 1, question: 'מה "אוקסימורון"?',                         answers: ['מילה בכמה משמעויות', 'שיתוף שני מושגים סותרים', 'חרוז', 'המחשה'], correctIndex: 1 },
  { id: 328, difficulty: '7-8', category: 'hebrew', points: 1, question: 'מה "קונפליקט" בסיפורת?',                  answers: ['הסיום', 'המתח/סכסוך שמניע את הסיפור', 'הגיבור', 'הרקע'],  correctIndex: 1 },
  { id: 329, difficulty: '7-8', category: 'hebrew', points: 1, question: 'מה ההבדל בין "גלוי" ל"סמוי"?',           answers: ['גלוי=נאמר ישירות, סמוי=רמוז', 'גלוי=חזק, סמוי=חלש', 'אין הבדל', 'גלוי=ישן, סמוי=חדש'], correctIndex: 0 },
  { id: 330, difficulty: '7-8', category: 'hebrew', points: 1, question: 'מה "אינטרטקסטואליות"?',                   answers: ['השוואת טקסטים', 'הפניה לטקסט אחר בתוך הטקסט', 'תרגום', 'ציטוט'],  correctIndex: 1 },
  { id: 331, difficulty: '7-8', category: 'hebrew', points: 1, question: 'מה "אנטיגיבור"?',                          answers: ['הנבל', 'גיבור שאינו מצטיין בסגולות קלאסיות', 'הגיבור הראשי', 'דמות משנית'], correctIndex: 1 },
  { id: 332, difficulty: '7-8', category: 'hebrew', points: 1, question: 'מה "עקידת יצחק" כסמל בספרות ישראלית?',   answers: ['סמל לגבורה', 'סמל לקורבן ואמונה', 'סמל לאהבת אב', 'סמל למדבר'],  correctIndex: 1 },
  { id: 333, difficulty: '7-8', category: 'hebrew', points: 1, question: 'מה "חרוז" בשירה?',                         answers: ['קצב', 'הקבלת צלילים בסוף שורות', 'חזרה על מילה', 'מבנה A-B'],  correctIndex: 1 },
  { id: 334, difficulty: '7-8', category: 'hebrew', points: 1, question: 'מה "פלאשבק"?',                             answers: ['קפיצה קדימה בזמן', 'חזרה לאחור בזמן', 'עצירת הזמן', 'זמן הווה'],  correctIndex: 1 },
  { id: 335, difficulty: '7-8', category: 'hebrew', points: 1, question: 'מה "טון" בטקסט?',                          answers: ['הנושא', 'הגישה הרגשית שהכותב מביע', 'הסגנון הלשוני', 'הסיום'],   correctIndex: 1 },
  { id: 336, difficulty: '7-8', category: 'hebrew', points: 1, question: 'מה "פרדוקס"?',                             answers: ['משפט שנראה סתרנותי אך מכיל אמת', 'גוזמה', 'שאלה רטורית', 'חרוז'],  correctIndex: 0 },
  { id: 337, difficulty: '7-8', category: 'hebrew', points: 1, question: 'מה ההבדל בין "יצירה אפית" ל"לירית"?',    answers: ['אפית=ארוכה, לירית=קצרה', 'אפית=מספרת עלילה, לירית=מבטאת רגשות', 'אין הבדל', 'אפית=שירה, לירית=פרוזה'], correctIndex: 1 },
  { id: 338, difficulty: '7-8', category: 'hebrew', points: 1, question: 'מה "מסגרת נרטיבית"?',                     answers: ['כותרת הסיפור', 'סיפור שבתוכו מוטמעים סיפורים אחרים', 'הפרק האחרון', 'ההקדמה'], correctIndex: 1 },
  { id: 339, difficulty: '7-8', category: 'hebrew', points: 1, question: 'מה "רמז מקראי" בספרות?',                  answers: ['ציטוט ישיר', 'הפניה לטקסט מקראי להוסיף עומק', 'תרגום ממקרא', 'ביקורת'],  correctIndex: 1 },
  { id: 340, difficulty: '7-8', category: 'hebrew', points: 1, question: 'מה "קתרזיס" לפי אריסטו?',                answers: ['הזדהות עם הגיבור', 'טיהור רגשי שחש הקורא/צופה', 'שיא העלילה', 'הסיום'],  correctIndex: 1 },

  // ===== עברית – ט-י (הבנת הנקרא) =====
  { id: 341, difficulty: '9-10', category: 'hebrew', points: 1, question: 'מה "זרם התודעה" (stream of consciousness)?', answers: ['תיאור מקום', 'טכניקת כתיבה המשקפת מחשבות ורגשות ספונטניים', 'מספר חיצוני', 'שיח ישיר'], correctIndex: 1 },
  { id: 342, difficulty: '9-10', category: 'hebrew', points: 1, question: 'מה ההבדל בין "סמל" ל"סימן"?',            answers: ['אין הבדל', 'סמל=ייצוג עמוק ותרבותי, סימן=הפניה מוסכמת פשוטה', 'סמל=חזותי, סימן=כתוב', 'סמל=ישן, סימן=מודרני'], correctIndex: 1 },
  { id: 343, difficulty: '9-10', category: 'hebrew', points: 1, question: 'מה "נרטיב לא אמין"?',                    answers: ['סיפור מוגזם', 'מספר שאינו מהימן לחלוטין', 'סיפור בדיוני', 'מספר אנונימי'],  correctIndex: 1 },
  { id: 344, difficulty: '9-10', category: 'hebrew', points: 1, question: 'מה "אקספוזיציה" בסיפור?',                answers: ['שיא העלילה', 'הצגת הרקע, הדמויות והמצב ההתחלתי', 'הסיום', 'הקונפליקט'],  correctIndex: 1 },
  { id: 345, difficulty: '9-10', category: 'hebrew', points: 1, question: 'מה "לייטמוטיב"?',                        answers: ['כלי מוזיקלי', 'מניע/נושא החוזר ביצירה כחוט מקשר', 'אנפורה', 'חרוז'],  correctIndex: 1 },
  { id: 346, difficulty: '9-10', category: 'hebrew', points: 1, question: 'מה "ז\'אנר"?',                           answers: ['כותב', 'סוג/קטגוריה ספרותית', 'תקופה', 'מגמה'],           correctIndex: 1 },
  { id: 347, difficulty: '9-10', category: 'hebrew', points: 1, question: 'מה מאפיין ספרות "מודרניסטית"?',          answers: ['עלילה ליניארית ברורה', 'שבירת מוסכמות, נרטיב מורכב, חקר תודעה', 'גיבורים קלאסיים', 'סיום מאושר'],  correctIndex: 1 },
  { id: 348, difficulty: '9-10', category: 'hebrew', points: 1, question: 'מה "עמדת הסופר"?',                       answers: ['מקום הכתיבה', 'השקפת עולמו שמשתקפת ביצירה', 'הז\'אנר', 'הסגנון'],  correctIndex: 1 },
  { id: 349, difficulty: '9-10', category: 'hebrew', points: 1, question: 'מה "הפואטיקה של אריסטו" עוסקת בה?',      answers: ['מוזיקה', 'עקרונות השירה והסיפורת', 'פילוסופיה', 'פוליטיקה'],  correctIndex: 1 },
  { id: 350, difficulty: '9-10', category: 'hebrew', points: 1, question: 'מה "בלדה"?',                             answers: ['שיר לירי אישי', 'שיר עלילתי עממי לרוב מחורז', 'פרוזה קצרה', 'מחזה'],  correctIndex: 1 },
  { id: 351, difficulty: '9-10', category: 'hebrew', points: 1, question: 'מה "מבנה טלסקופי"?',                    answers: ['סיפור ישיר קדימה', 'סיפורים המוטמעים זה בתוך זה', 'חזרה לאחור', 'עלילה מקבילה'],  correctIndex: 1 },
  { id: 352, difficulty: '9-10', category: 'hebrew', points: 1, question: 'מה "ספרות זרם התודעה" הושפעה מ?',        answers: ['מרקסיזם', 'פסיכואנליזה פרוידיאנית', 'רומנטיקה', 'ריאליזם'],  correctIndex: 1 },
  { id: 353, difficulty: '9-10', category: 'hebrew', points: 1, question: 'מה "כינוי"?',                            answers: ['תואר', 'מילה המחליפה שם עצם', 'פועל עזר', 'מילת יחס'],  correctIndex: 1 },
  { id: 354, difficulty: '9-10', category: 'hebrew', points: 1, question: 'מה ייחודי ל"שיר לא מחורז" (חופשי)?',    answers: ['אין משמעות', 'אין קצב וחרוז קבועים, חופש ביטוי מלא', 'קצר מאוד', 'תמיד עצוב'],  correctIndex: 1 },
  { id: 355, difficulty: '9-10', category: 'hebrew', points: 1, question: 'מה "אובייקטיביזציה" בספרות?',           answers: ['תיאור רגשי', 'ייצוג רגשות דרך אובייקטים חיצוניים', 'גוזמה', 'אירוניה'],  correctIndex: 1 },
  { id: 356, difficulty: '9-10', category: 'hebrew', points: 1, question: 'מה "פיגורה" (figure of speech)?',        answers: ['דמות בסיפור', 'שימוש לא מילולי בשפה לצרכי אפקט', 'קצב', 'נרטיב'],  correctIndex: 1 },
  { id: 357, difficulty: '9-10', category: 'hebrew', points: 1, question: 'מה "הנחת יסוד" בטיעון?',                answers: ['מסקנה', 'הנחה שמוצגת כאמת בלי הוכחה', 'דוגמה', 'ראיה'],  correctIndex: 1 },
  { id: 358, difficulty: '9-10', category: 'hebrew', points: 1, question: 'מה "מחזה אבסורד"?',                     answers: ['מחזה מצחיק', 'מחזה המדגיש חוסר משמעות הקיום', 'מחזה היסטורי', 'טרגדיה'],  correctIndex: 1 },
  { id: 359, difficulty: '9-10', category: 'hebrew', points: 1, question: 'מה "אמפתיה" ב"הבנת הנקרא"?',            answers: ['הסכמה עם הכותב', 'הזדהות עם רגשות הדמות', 'ביקורת', 'ניתוח'],  correctIndex: 1 },
  { id: 360, difficulty: '9-10', category: 'hebrew', points: 1, question: 'מה "אפיגרף"?',                           answers: ['הפרק האחרון', 'ציטוט בפתח היצירה המרמז על נושאה', 'כותרת', 'הקדשה'],  correctIndex: 1 },

  // ===== עברית – י"א-י"ב (הבנת הנקרא) =====
  { id: 361, difficulty: '11-12', category: 'hebrew', points: 1, question: 'מה "דקונסטרוקציה" כגישה ביקורתית?',    answers: ['בנייה מחדש', 'פירוק הטקסט לחשוף סתירות פנימיות', 'ניתוח דמויות', 'השוואת טקסטים'],  correctIndex: 1 },
  { id: 362, difficulty: '11-12', category: 'hebrew', points: 1, question: 'מה "ביקורת פמיניסטית" בספרות?',        answers: ['ניתוח שפה', 'קריאת טקסטים מנקודת מבט מגדרית', 'ביקורת מרקסיסטית', 'ניתוח היסטורי'],  correctIndex: 1 },
  { id: 363, difficulty: '11-12', category: 'hebrew', points: 1, question: 'מה "אינטנציית המחבר" בביקורת ספרותית?', answers: ['מה הקורא מבין', 'הכוונה המקורית של הכותב', 'מה הטקסט אומר כשלעצמו', 'השפעת הטקסט'],  correctIndex: 1 },
  { id: 364, difficulty: '11-12', category: 'hebrew', points: 1, question: 'מה "ביקורת חדשה" (New Criticism)?',    answers: ['ביקורת עכשווית', 'גישה המתמקדת בטקסט בלבד ללא הקשר', 'ביקורת פמיניסטית', 'ביקורת מרקסיסטית'],  correctIndex: 1 },
  { id: 365, difficulty: '11-12', category: 'hebrew', points: 1, question: 'מה מאפיין ספרות "פוסטמודרנית"?',      answers: ['נרטיב ליניארי', 'רב-קוליות, מטאפיקציה, ערעור על אמת', 'גיבורים אידיאליים', 'סיום חד-משמעי'],  correctIndex: 1 },
  { id: 366, difficulty: '11-12', category: 'hebrew', points: 1, question: 'מה "מטאפיקציה"?',                      answers: ['פיקציה מדעית', 'יצירה המדברת על עצמה כיצירה', 'ביוגרפיה', 'מסה'],  correctIndex: 1 },
  { id: 367, difficulty: '11-12', category: 'hebrew', points: 1, question: 'מה "הגמוניה תרבותית" לפי גרמשי?',      answers: ['שלטון צבאי', 'שליטה חברתית דרך ערכים ותרבות', 'שפה דומיננטית', 'כלכלה'],  correctIndex: 1 },
  { id: 368, difficulty: '11-12', category: 'hebrew', points: 1, question: 'מה "גוף בטקסט" בתיאוריה פמיניסטית?',  answers: ['תיאור פיזי', 'הגוף כמקום של זהות, כוח ופוליטיקה', 'ביולוגיה', 'רפואה'],  correctIndex: 1 },
  { id: 369, difficulty: '11-12', category: 'hebrew', points: 1, question: 'מה "דיאלקטיקה" ב"הבנת הנקרא"?',       answers: ['שיטת שאלות ותשובות להגיע לאמת', 'ניגוד בין דמויות', 'מבנה השיר', 'קונפליקט'],  correctIndex: 0 },
  { id: 370, difficulty: '11-12', category: 'hebrew', points: 1, question: 'מה "ספרות קנון"?',                     answers: ['ספרות דתית', 'יצירות שנחשבות חיוניות בתרבות', 'ספרות לילדים', 'ספרות עממית'],  correctIndex: 1 },
  { id: 371, difficulty: '11-12', category: 'hebrew', points: 1, question: 'מה "ייצוג ה-אחר" בספרות פוסטקולוניאלית?', answers: ['גיבור שלילי', 'כיצד התרבות הדומיננטית מתארת קבוצות שוליות', 'דמות משנית', 'מספר'],  correctIndex: 1 },
  { id: 372, difficulty: '11-12', category: 'hebrew', points: 1, question: 'מה "קריאה סימפטומטית"?',               answers: ['קריאה מהירה', 'קריאה שמחפשת את מה שהטקסט מסתיר', 'קריאה ליניארית', 'קריאה פשוטה'],  correctIndex: 1 },
  { id: 373, difficulty: '11-12', category: 'hebrew', points: 1, question: 'מה "ביוגרפי-ביקורתי" כגישה?',         answers: ['ניתוח פנימי של הטקסט', 'קשר בין חיי הסופר ליצירתו', 'ביקורת תרבותית', 'ניתוח שפה'],  correctIndex: 1 },
  { id: 374, difficulty: '11-12', category: 'hebrew', points: 1, question: 'מה "מרחב" ב"ביקורת הנקרא"?',           answers: ['תיאור הנוף', 'המרחב כסמל לזהות, כוח ומגדר', 'הגדרה פיזית', 'רקע'],  correctIndex: 1 },
  { id: 375, difficulty: '11-12', category: 'hebrew', points: 1, question: 'מה "אינטרסוביקטיביות"?',               answers: ['שיח בין שניים', 'משמעות הנוצרת בין סובייקטים שונים', 'ביקורת', 'ניתוח'],  correctIndex: 1 },
  { id: 376, difficulty: '11-12', category: 'hebrew', points: 1, question: 'מה "שיח" (discourse) לפי פוקו?',       answers: ['שיחה', 'מערכת של ידע וכוח המעצבת את המציאות', 'טקסט', 'נרטיב'],  correctIndex: 1 },
  { id: 377, difficulty: '11-12', category: 'hebrew', points: 1, question: 'מה "ריבוי קולות" (polyphony) לפי בחטין?', answers: ['שירת מקהלה', 'מספר קולות/נקודות מבט שווי ערך ביצירה', 'מספר בגוף שלישי', 'אנפורה'],  correctIndex: 1 },
  { id: 378, difficulty: '11-12', category: 'hebrew', points: 1, question: 'מה "ספרות מגמה"?',                     answers: ['ספרות ז\'אנר', 'ספרות המשרתת מטרה אידיאולוגית/חברתית', 'ספרות קלאסית', 'ספרות ילדים'],  correctIndex: 1 },
  { id: 379, difficulty: '11-12', category: 'hebrew', points: 1, question: 'מה "הסובייקט הלירי"?',                 answers: ['הכותב עצמו', 'קול הדובר בשיר, לאו דווקא הסופר', 'הקורא', 'הנושא'],  correctIndex: 1 },
  { id: 380, difficulty: '11-12', category: 'hebrew', points: 1, question: 'מה "קריאת אבל" (mourning reading)?',   answers: ['קריאה עצובה', 'קריאה המכירה בחוסר האפשרות לשחזר את כוונת המחבר', 'ביקורת', 'פרשנות'],  correctIndex: 1 },

  // ===== עברית – אוניברסיטה (הבנת הנקרא) =====
  { id: 381, difficulty: 'university', category: 'hebrew', points: 1, question: 'מה "התפנות מהמחבר" (death of the author) לפי רולאן בארת?', answers: ['המחבר מת', 'הטקסט עצמאי ממחברו, הקורא יוצר את המשמעות', 'הטקסט אינו חשוב', 'הביוגרפיה חשובה'],  correctIndex: 1 },
  { id: 382, difficulty: 'university', category: 'hebrew', points: 1, question: 'מה "ביקורת פוסטקולוניאלית"?',      answers: ['ביקורת של ספרות מאוחרת', 'ניתוח השפעת הקולוניאליזם על ספרות ותרבות', 'ביקורת מרקסיסטית', 'גישה פמיניסטית'],  correctIndex: 1 },
  { id: 383, difficulty: 'university', category: 'hebrew', points: 1, question: 'מה "מיתוס" לפי רולאן בארת ב"מיתולוגיות"?', answers: ['סיפור עתיק', 'מערכת של משמעויות המחביאה אידיאולוגיה בורגנית', 'אגדת עם', 'דת'],  correctIndex: 1 },
  { id: 384, difficulty: 'university', category: 'hebrew', points: 1, question: 'מה "הפרדיגמה" לפי תומאס קון?',     answers: ['מסגרת מחשבתית שמנחה מחקר מדעי', 'תיאוריה ספרותית', 'שיטת כתיבה', 'ניתוח נרטיב'],  correctIndex: 0 },
  { id: 385, difficulty: 'university', category: 'hebrew', points: 1, question: 'מה "הטרוגלוסיה" לפי בחטין?',       answers: ['שפה אחידה', 'ריבוי שפות וסגנונות בתוך טקסט', 'שפה זרה', 'שיח'],  correctIndex: 1 },
  { id: 386, difficulty: 'university', category: 'hebrew', points: 1, question: 'מה "ביקורת לאקאניאנית"?',          answers: ['ביקורת שפה', 'קריאה דרך תיאוריית הפסיכואנליזה של לאקאן', 'ביקורת מרקסיסטית', 'ביקורת פמיניסטית'],  correctIndex: 1 },
  { id: 387, difficulty: 'university', category: 'hebrew', points: 1, question: 'מה "הבדל" (differance) לפי דרידה?', answers: ['הבדל משמעות', 'הדחיה הנצחית של משמעות, שפה כמערכת הבדלים', 'ניגוד', 'אנטיתזה'],  correctIndex: 1 },
  { id: 388, difficulty: 'university', category: 'hebrew', points: 1, question: 'מה "ביקורת ניו היסטוריסיזם"?',    answers: ['ניתוח עצמאי של הטקסט', 'הטמעת הטקסט בהקשר ההיסטורי והתרבותי', 'ביקורת שפה', 'ביקורת פסיכולוגית'],  correctIndex: 1 },
  { id: 389, difficulty: 'university', category: 'hebrew', points: 1, question: 'מה "כיוון מחקר קוויר" בספרות?',   answers: ['ספרות רומנטית', 'ניתוח זהות מינית ומגדרית בטקסטים', 'ביקורת פמיניסטית בלבד', 'ניתוח דמויות'],  correctIndex: 1 },
  { id: 390, difficulty: 'university', category: 'hebrew', points: 1, question: 'מה "אקוקריטיקה" (ecocriticism)?', answers: ['ביקורת כלכלית', 'מחקר יחסי ספרות וסביבה/טבע', 'ביקורת אקולוגית של שפה', 'ניתוח מרחב'],  correctIndex: 1 },
];

@Injectable({ providedIn: 'root' })
export class TriviaService {
  getQuestion(id: number): TriviaQuestion | undefined {
    return QUESTIONS.find(q => q.id === id);
  }

  getRandomQuestions(difficulty: Difficulty, category: TriviaCategory, count: number): TriviaQuestion[] {
    const pool = QUESTIONS.filter(q => q.difficulty === difficulty && q.category === category);
    const shuffled = [...pool].sort(() => Math.random() - 0.5);
    return shuffled.slice(0, Math.min(count, shuffled.length));
  }
}
